# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-22 10:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='昵称')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('telephone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}$', '请输入正确的号码')], verbose_name='手机号')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('sex', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
                ('school', models.CharField(blank=True, max_length=50, null=True, verbose_name='学校名')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='现居地址')),
                ('hometown', models.CharField(blank=True, max_length=255, null=True, verbose_name='家乡')),
            ],
            options={
                'verbose_name': '用户管理',
                'verbose_name_plural': '用户管理',
                'db_table': 'user',
            },
        ),
    ]
